### ISSUE TITLE
Can't run sample code

### ISSUE THREAD

**Issue by julianonunes** [pythonforfacebook/facebook-sdk#204]
I've used the commands from https://facebook-sdk.readthedocs.org/en/latest/install.html to install the sdk, which is recognized by PyCharm, but when I run the project as app engine website it gives me this error:

INFO     2015-03-29 22:18:30,182 module.py:737] default: "GET / HTTP/1.1" 500 -
ERROR    2015-03-29 22:19:07,986 wsgi.py:263] 
Traceback (most recent call last):
  File "/opt/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/opt/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/opt/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/juliano/Documents/Projetos/Fb2/fb.py", line 1, in <module>
    import facebook
ImportError: No module named facebook
INFO     2015-03-29 22:19:08,003 module.py:737] default: "GET / HTTP/1.1" 500 -

**Comment by martey** [comment]
It looks like you've already received an answer to [the question you posted on StackOverflow](http://stackoverflow.com/q/29336499/113527), so I am closing this issue.
