### ISSUE TITLE
Google App Engine RuntimeError: error('illegal IP address string passed to inet_pton',)

### ISSUE THREAD

**Issue by chrisrote** [pythonforfacebook/facebook-sdk#214]
First off, thanks, love this sdk. In python google app engine, I continue to get the following error message with the login button, do we need to change the port number somewhere in the requests module?

Google App Engine RuntimeError: error('illegal IP address string passed to inet_pton',)

**Comment by martey** [comment]
Do you have access to the complete traceback? If so, could you provide it?

**Comment by chrisrote** [comment]
gotya:
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/chrisrote/chat_helpa/controllers/home.py", line 125, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/chrisrote/chat_helpa/controllers/home.py", line 176, in get
    current_user=self.current_user
  File "/Users/chrisrote/chat_helpa/controllers/home.py", line 87, in current_user
    FACEBOOK_APP_SECRET)
  File "/Users/chrisrote/chat_helpa/facebook/__init__.py", line 344, in get_user_from_cookie
    app_id, app_secret)
  File "/Users/chrisrote/chat_helpa/facebook/__init__.py", line 401, in get_access_token_from_code
    code, redirect_uri, app_id, app_secret)
  File "/Users/chrisrote/chat_helpa/facebook/__init__.py", line 279, in get_access_token_from_code
    return self.request("oauth/access_token", args)
  File "/Users/chrisrote/chat_helpa/facebook/__init__.py", line 225, in request
    files=files)
  File "/Users/chrisrote/chat_helpa/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/chrisrote/chat_helpa/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chrisrote/chat_helpa/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chrisrote/chat_helpa/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/chrisrote/chat_helpa/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/chrisrote/chat_helpa/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Users/chrisrote/chat_helpa/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/Users/chrisrote/chat_helpa/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/Users/chrisrote/chat_helpa/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/chrisrote/chat_helpa/requests/packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/remote_socket/_remote_socket.py", line 339, in getaddrinfo
    canonical=(flags & AI_CANONNAME))
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/remote_socket/_remote_socket.py", line 212, in _Resolve
    canon, aliases, addresses = _ResolveName(name, families)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/remote_socket/_remote_socket.py", line 230, in _ResolveName
    apiproxy_stub_map.MakeSyncCall('remote_socket', 'Resolve', request, reply)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 95, in MakeSyncCall
    return stubmap.MakeSyncCall(service, call, request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 329, in MakeSyncCall
    rpc.CheckSuccess()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_rpc.py", line 157, in _WaitImpl
    self.request, self.response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 201, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 235, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
RuntimeError: error('illegal IP address string passed to inet_pton',)

**Comment by martey** [comment]
Maybe try some of the suggestions in https://stackoverflow.com/a/28544823/113527 ?

Since [requests does not support Google App Engine](https://github.com/kennethreitz/requests/issues/1905#issuecomment-34365937), it is extremely likely that we won't in the future either. There are too many open issues that only affect GAE, and it doesn't look like anyone has the bandwidth to deal with them.

**Comment by chrisrote** [comment]
That's too bad. GAE is great, if you can get it to work :) Thank you for your quick help, martey, will post back here when I figure it out

**Comment by chrisrote** [comment]
I'm just going to abandon this method and re-create the methods I need using the urlfetch API in GAE. Thanks again for your help

**Comment by lucasrangit** [comment]
@chrisrote When you figure it out please share how via the [Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook). I figured out how and [got my GAE app upgraded](https://github.com/lucasrangit/FriendsByLocation/commit/68383f24a75246ecf2b4fca50c775e368354010f) but it was a pain.

**Comment by chrisrote** [comment]
@lucasrangit thanks, I will share to the group. I am currently just using the login system (not a lot of graph scraping) which is luckily fairly simple

**Comment by chrisrote** [comment]
Just a note here for future GAE users, I ran into the same issue. I would recommend using https://github.com/crhym3/simpleauth I found Simple Auth and made some adjustments to get my app up and running. There are definitely improvements to be made, but it should get you to a good starting place.

**Comment by chrisrote** [comment]
@lucasrangit I finally added my solution to the google group you suggested, sorry for the delay.

**Comment by seawolf42** [comment]
I'm dealing with this same issue, and it appears to be the subject of another thread and is being actively worked on. Look at:
* [HTTPS not working on Google App Engine](https://github.com/kennethreitz/requests/issues/1905)

... which references:
* [Add AppEngineAdapter for GAE users](https://github.com/sigmavirus24/requests-toolbelt/pull/114)
* [Adds a monkeypatch() function that ensures all Sessions use the AppEngineAdapter compatibility class.](https://github.com/sigmavirus24/requests-toolbelt/pull/119)
