### ISSUE TITLE
Python 3.4: invalid syntax error in facebook.py (line 222)

### ISSUE THREAD

**Issue by pulindesai1** [pythonforfacebook/facebook-sdk#233]
Tried to run the example and I get following syntax error.

thanks,

____
C:\Python34\fbsdka>flask\Scrips\python run.py
The system cannot find the path specified.

C:\Python34\fbsdka>flask\Scripts\python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from app import app, db
  File "C:\Python34\fbsdka\app\__init__.py", line 8, in <module>
    from app import views, models
  File "C:\Python34\fbsdka\app\views.py", line 1, in <module>
    from facebook import get_user_from_cookie, GraphAPI
  File "C:\Python34\fbsdka\flask\lib\site-packages\facebook.py", line 222
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax

**Comment by martey** [comment]
Version 0.4.0 does not support Python 3. Please upgrade to git master.
